debug: true
dynamicRegistration:
  config:
  - authenticationPassphrase: V@p0rIO!
    authenticationProtocol: SHA
    deviceTags:
    - serverName:networkUps
    endpoint: 10.193.18.241
    model: SU10000RT3UPM
    port: 161
    privacyPassphrase: V@p0rIO!
    privacyProtocol: AES
    userName: portal
    version: v3
network:
  address: :5003
  type: tcp
settings:
  cache:
    enabled: true
    ttl: 5m
  mode: serial
  read:
    buffer: 1024
    delay: 500ms
    interval: 90s
  write:
    enabled: false
version: 3
